name = "calista-store"
main = "src/index.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "kapra_store_db"
database_id = "ea0cb1a3-42fd-44c0-b4aa-ab6c977bcd89"
